source 'http://rubygems.org'

gem 'rails', '~> 5.1.4'
gem 'puma-daemon', require: false
gem 'puma',  '~> 5'
gem 'uglifier'
gem 'coffee-rails'
# gem 'coffee-script-source', '1.8.0'
gem 'libv8'
#gem 'compass-rails'
gem 'execjs'
gem 'resque'
gem 'resque-pool'
gem 'god'
gem 'bootstrap-sass'
gem 'bootstrap-material-design'
gem 'sass-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'materialize'
gem 'materialize-sass'
gem 'best_in_place'

gem 'bcrypt'
gem 'devise'
gem 'uuid'
gem 'pg'
gem 'exception_notification'

gem 'friendly_id'
gem 'cancancan'
gem 'prawn'#,                    '~> 1.0.0.rc1'
gem 'prawn-table'
gem 'later_dude',               '>= 0.3.1'
gem 'icalendar'
gem 'kaminari'

# gems for google sync
gem 'omniauth-google-oauth2'
gem 'google-api-client'
gem 'rest-client'
gem 'nokogiri'


group :development, :archive_dev do
  gem 'rails_best_practices',   require: false
  gem 'letter_opener'
  gem 'brakeman'
  gem 'test-unit'
  gem 'listen'
end

group :test do
  gem 'turn',                   require: false
  gem 'mocha',                  require: false
end
