source 'http://rubygems.org'

# gem 'best_in_place'
gem 'benchmark', require: false
gem 'bootstrap-material-design'
gem 'bootstrap-sass'
gem 'coffee-rails', '4.2.2'
gem 'rails', '~> 6.1.7'
gem 'rack', '~> 2.2.22'
gem 'sprockets', '~> 4.0'
gem 'sass-rails', '~> 6.0'
gem "jsbundling-rails"
gem 'execjs'
gem 'ffi', '< 1.17.0'
gem 'god'
gem 'jquery-rails'
gem 'jquery-ui-rails'

gem 'materialize'
gem 'materialize-sass'
gem 'matrix'
gem 'puma', '~> 5.0'
gem 'resque'
gem 'resque-pool'
gem 'uglifier'

gem 'bcrypt'
gem 'devise'
gem 'exception_notification', '~> 4.5'
gem 'pg', '>= 1.5.4'
gem 'uuid'

gem 'cancancan'
gem 'friendly_id'
gem 'icalendar'
gem 'kaminari'
gem 'later_dude', '>= 0.3.1'
gem 'prawn' # ,                    '~> 1.0.0.rc1'
gem 'prawn-table'

# gems for google sync
gem 'google-api-client'
gem 'nokogiri'
gem 'omniauth-google-oauth2'
gem 'rest-client'

group :development, :archive_dev do
  gem 'brakeman'
  gem 'letter_opener'
  gem 'listen'
  gem 'rails_best_practices', require: false
  gem 'test-unit'
  gem 'rspec-rails'
  gem 'pry-byebug'
end

group :test do
  gem 'mocha',                  require: false
  gem 'turn',                   require: false
  gem 'playwright-ruby-client'
  gem 'capybara'
end

gem 'bundler', '~> 2.2'
gem 'drb'
