services:

  redis-service:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

  logenhelfer:
    build: ./rails-app/
    ports:
      - "9876:9876"
    networks:
      - logenhelfer
    environment:
      DATABASE_URL: ${DB_URL:-postgres-db}
      RAILS_ENV: ${RAILS_ENV:?error}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS:-5}
      PUMA_BIND: ${PUMA_BIND:-tcp://0.0.0.0:9876}
      RAILS_LOG_TO_STDOUT: true

volumes:
  postgresvolume: {}
  cache:
    driver: local

networks:
  logenhelfer:
    driver: bridge
    enable_ipv6: false
