upstream fwze {
	server 127.0.0.1:9876;
	server 127.0.0.1:9876;
	server 127.0.0.1:9876;
	server 127.0.0.1:9876;
	server 127.0.0.1:9876;
}

server{
  listen [::]:80;
  server_name fwze.disp.logenhelfer.de intern.fwze.de;
  include /etc/nginx/letsencrypt.conf;
  include /etc/nginx/default.conf;

  rewrite ^(.*) https://$host$1 permanent;
}

server {
  listen [::]:443;
  ssl on;
  client_max_body_size 512M;

  server_name intern.fwze.de;

  include /etc/nginx/letsencrypt.conf;
  include /etc/nginx/default.conf;

  #ssl_certificate  /etc/letsencrypt/live/fwze.disp.logenhelfer.de/fullchain.pem;
  #ssl_certificate_key  /etc/letsencrypt/live/fwze.disp.logenhelfer.de/privkey.pem;

  ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
	ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
  ssl_session_timeout  5m;
  ssl_prefer_server_ciphers   on;

  access_log  /var/log/nginx/fwze.disp.logenhelfer.de.access.log;
  error_log   /var/log/nginx/fwze.disp.logenhelfer.de.error.log;

  root   /srv/www/logenhelfer.de/fwze/public;

  location / {
         try_files $uri @ruby;
  }
  real_ip_header X-Real-IP;
  real_ip_recursive on;
  location @ruby {
          proxy_set_header  X-Real-IP  $remote_addr;
          proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header  Host $http_host;
	  proxy_set_header X-Forwarded-Proto https;
          proxy_redirect off;
          proxy_read_timeout 300;
          proxy_pass http://fwze;
  }

  location ~ /\.ht {
          deny  all;
  }
  error_page 500 /500.html;
  error_page 502 /502.html;
  error_page 404 /404.html;
}