
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "pg.elsbroek.com") %>
  username: <%= ENV.fetch("POSTGRES_USER", "fwzeintern") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "fwzeintern") %>
  database: <%= ENV.fetch("POSTGRES_DB", "fwzeintern") %>
  pool: 5

fwze:
  <<: *default
  database: fwzeintern

development:
  <<: *default
  database: fwzeintern_development

test:
  <<: *default
  database: fwzeintern_test