# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28535e13329ad41d9cd2d4861580d5a7cf4d86e369980507e924926b99598b1603e127db0c076c65820d827635b5a90427a946c9234850c04f5c57c304a87231

test:
  secret_key_base: 525bab516394679c16fea559da742aa764748c43732b2bd6e11e9b3fa7356085098300502f68ea3b4e721e4dddec14965bb34ecc7e91a2d2b4cac193254143c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
