# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f119c15618ff6270c3dae64d8ca16d54ad333d37493fe0a9f1228df86439f5843b313da36eae99b260b36d76c86bb1771db022d668412b88a1b8d85cef899bef

test:
  secret_key_base: 5e2a3361c389bc5da706784965ded9c87a6dbf9bd3799a1649067644c002b73793d77266643b4c8461aee422a8b2aa1da6ff09daf502b6ff6da92bb8a1d54f9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
